postgresql:
  postgresqlPostgresPassword: temppassword
  postgresqlUsername: user

  securityContext:
    fsGroup: 0

  containerSecurityContext:
    runAsUser: 0
    
  volumePermissions:
    enabled: true

  persistence:
    enabled: false
